# Generated by Django 4.1.10 on 2023-10-01 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_remove_field_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='field',
            name='description',
            field=models.TextField(),
        ),
    ]
