# Generated by Django 4.1.10 on 2023-10-01 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0004_alter_field_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfolio',
            name='details',
        ),
        migrations.AddField(
            model_name='fieldvalue',
            name='portfolio',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='portfolio.portfolio'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
