# Generated by Django 4.1.10 on 2023-10-01 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0005_remove_portfolio_details_fieldvalue_portfolio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fieldvalue',
            name='field',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='portfolio.field'),
        ),
    ]
